# Generated by Django 5.2.6 on 2025-09-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: 1º Período", max_length=100, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponenteCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Ex: Anatomia Humana", max_length=200),
                ),
                (
                    "numero_questoes_prova",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número de questões a serem selecionadas para a prova.",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="questoes.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_base",
                    models.TextField(
                        blank=True,
                        help_text="Texto ou contexto que serve de base para a questão.",
                        null=True,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem opcional para a questão.",
                        null=True,
                        upload_to="imagens_questoes/",
                    ),
                ),
                (
                    "enunciado",
                    models.TextField(
                        help_text="O enunciado ou pergunta principal da questão."
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Explicação detalhada sobre o gabarito e as alternativas."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente de Validação"),
                            ("APROVADA", "Aprovada"),
                            ("REPROVADA", "Reprovada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "componente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questoes",
                        to="questoes.componentecurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(
                        help_text="Texto da alternativa (A, B, C, D ou E).",
                        max_length=500,
                    ),
                ),
                (
                    "eh_correta",
                    models.BooleanField(
                        default=False,
                        help_text="Marque esta opção se esta for a alternativa correta (gabarito).",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="questoes.questao",
                    ),
                ),
            ],
        ),
    ]
